addons:
  postgresql: 9.6

before_script:
  - psql -c 'create database instagram-challenge_test;' -U postgres

language: ruby
rvm:
  - 2.6.0

script:
  - bundle exec rails db:migrate RAILS_ENV=test
  - bundle exec rake spec
